# fly.toml app configuration file generated for homey-recipes on 2024-03-06T10:19:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'homey-recipes'
primary_region = 'mad'

[build]

[http_service]
auto_stop_machines = 'stop'
internal_port = 3000
force_https = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[mounts]
source = 'homey_recipes_data'
destination = '/data'

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
